trigger:
    batch: true
    branches:
        include:
        - main
        - develop
    paths:
        include:
        - "./Shravan/Assessmemt_API_09-02-2023/*"

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""

stages:
- template: templates/stage_level_templates/test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: Shravan/Book_ThreeTierArchitecture_API/Book_ThreeTierArchitecture_API.sln #${{variables.projectFolder}}
    buildOutputFolder: $(BUILDOUTPUTFOLDER) #${{variables.buildOutputFolder}}
    sourceFolder: $(SOURCEFOLDER) #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    

- template: templates/stage_level_templates/az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
    vmImageName : $(VMIMAGE) #${{variables.vmImage}}
    azureSubscription : "Visual Studio Enterprise Subscription – MPN(Interns)"
    resourceGroup : "Shravan"
    bicepFilePath : "Shravan/Book_ThreeTierArchitecture_API/infrastructure/main.bicep"
    parameterFilePath : "Shravan/Book_ThreeTierArchitecture_API/infrastructure/main.parameters.dev.json"
    jobName : "resourcedeployment"
    jobDescription : "deployemnt of resources"
    scriptType : "bash"
    environment: 'dev'
    deploy: true

#- template: templates/stage_level_templates/app_deployment_stage_template.yml #stage template for application deployment
#  parameters:
#    serviceConnection: 'Visual Studio Enterprise Subscription – MPN ( YousufAli& Harsha) (04f97656-0abc-4052-bd6e-eab5cd53b9f0)'
#    subscriptionId: '04f97656-0abc-4052-bd6e-eab5cd53b9f0'
#    environment: 'dev'
#    appType: 'webApp'